<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LavaGang.MelonLoader" Version="0.7.3" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy $(ProjectDir)bin\$(Configuration)\net6.0\* $(SolutionDir)x64\$(Configuration)\" />
  </Target>

</Project>
